### ISSUE TITLE
What are the x,y columns in the txt files of the datasets?

### ISSUE THREAD

**Issue by igygi** [FGiuliari/Trajectory-Transformer#11]
Hi, 

I'm new to the field of trajectory prediction and would like to understand the format of the dataset. May I ask what the x and y columns in the txt files are? Are they displacements (in pixels? meters?), velocities, or x and y center points?

Thank you.

**Comment by FGiuliari** [comment]
Hi,
the column are
frame id | person id | x position (in world coords, in meters) |  y position (in world coords, in meters)

The dataset txt files are taken the ones from the social gan repository.

There was one other repository (scene lstm  if I remember correctlyt) that also had the homography matrices to go from world coordinates to image coordinates.
