### ISSUE TITLE
Clarification regarding the prediction dimension

### ISSUE THREAD

**Issue by NehaPusalkar** [FGiuliari/Trajectory-Transformer#15]
Hello,

Thanks for sharing your work and codebase.
I have a question in the train_individualTF.py script. Could you tell the reason, why you add that third column of zeros (target_c) in line 153 while creating dec_inp. Does that help in the masking?

Thanks!

**Comment by FGiuliari** [comment]
Hello,
we add a 3rd feature to simulate the "start_of_sequence" token as is the case for NLP tasks.
The first input to the decoder will always be [0,0,1] and all the subsequent element will be [dx,dy,0].
