### ISSUE TITLE
Trajnet Challenge Dataset

### ISSUE THREAD

**Issue by Epicato** [FGiuliari/Trajectory-Transformer#24]
Hi! Thanks for your great work!
Since the website of the Trajnet Benchmark is not working anymore: http://trajnet.stanford.edu/,  I'm wondering whether you could provide the dataset of Trajnet Challenge or  the way to split the dataset of Stanford Drone Dataset in Trajnet Challenge?
Looking forward to your reply!

**Comment by FGiuliari** [comment]
Hi Epicato, 
I'm sorry but I don't have the data for the trajnet challenge anymore. 
With a quick search maybe these can be of help https://github.com/vita-epfl/trajnetplusplusdataset/tree/master/data/trajnet_original.
But I'm not sure whether those are already divided into train/val/test sets, also if I recall correctly the evaluation was server-side.
